spring:
  profiles:
    active: pg,mail
server:
  port: 8081
remoteService:
#  url: "http://localhost:5002"
  url: "http://172.30.9.31:5000"
  user: "admin"
  password: "password"
token:
  recover-clean-in-sec: "3600"
scheduled:
  broken-machines: "25000"
  update-batch: "20000"
  repairing-machines: "27000"
  new-requests: "30000"
  queue-view: "35000"
  telegram-bot-mailing: "20000"
default-user:
  login: "admin"
  password: "admin"
  email: "admin-user-42-user-admin@gmail.com"
  full-name: "Админ Админович Админов"
telegram:
  link: "null"
  token: "null"
generators:
  message: false
  telegram: false
  product: false
  request: false
  request-positions: false
  vacancy: false
  vacancy-respond: false
  vacancy-respond-online: false
  positions: true
  competence: true
  matrixCompetence: true