spring:
  profiles:
    active: pg,mail
server:
  port: 8081
remoteService:
  url: "http://localhost:5002"
  user: "admin"
  password: "password"
token:
  recover-clean-in-sec: "3600"
scheduled:
  broken-machines: "25000"
  update-batch: "20000"
  repairing-machines: "27000"
  new-requests: "30000"
  queue-view: "35000"
  telegram-bot-mailing: "20000"
default-user:
  login: "admin"
  password: "admin"
  email: "admin-user-42-user-admin@gmail.com"
  full-name: "Админ Админович Админов"
telegram:
  link: "http://t.me/AtomicHunterBot"
  token: "5729000727:AAEk3vHl_00K0ARTesyNpkaFN2gNlxAN4Ds"
generators:
  message: false
  telegram: true
  product: false
  request: false
  request-positions: false
  vacancy: false
  vacancy-respond: true
  vacancy-respond-online: true
  positions: true
  competence: true
  matrixCompetence: true